"use strict";

// 出題データの原本。クイズ中は配列を複製して使用します。
const words = [
  { word: "礼堂", pinyin: "lǐtáng", meaning: "講堂、式場", lesson: 1 },
  { word: "就", pinyin: "jiù", meaning: "まさに、まさしく", lesson: 1 },
  { word: "参加", pinyin: "cānjiā", meaning: "参加する", lesson: 1 },
  { word: "开学", pinyin: "kāixué", meaning: "学校が始まる", lesson: 1 },
  { word: "典礼", pinyin: "diǎnlǐ", meaning: "儀式", lesson: 1 },
  { word: "新生", pinyin: "xīnshēng", meaning: "新入生", lesson: 1 },
  { word: "怎么", pinyin: "zěnme", meaning: "どうして", lesson: 1 },
  { word: "穿", pinyin: "chuān", meaning: "着る", lesson: 1 },
  { word: "西装", pinyin: "xīzhuāng", meaning: "スーツ、背広", lesson: 1 },
  { word: "服装", pinyin: "fúzhuāng", meaning: "服装", lesson: 1 },
  { word: "自由", pinyin: "zìyóu", meaning: "自由である", lesson: 1 },
  { word: "好", pinyin: "hǎo", meaning: "非常に、なんと", lesson: 1 },
  { word: "羡慕", pinyin: "xiànmù", meaning: "うらやむ", lesson: 1 },
  { word: "一定", pinyin: "yídìng", meaning: "必ず", lesson: 1 },

  { word: "晚上", pinyin: "wǎnshang", meaning: "晩、夜", lesson: 2 },
  { word: "如果", pinyin: "rúguǒ", meaning: "もしも～", lesson: 2 },
  { word: "方便", pinyin: "fāngbiàn", meaning: "便利である", lesson: 2 },
  { word: "～的话", pinyin: "～dehua", meaning: "～ならば", answers: ["～的话", "的话"], lesson: 2 },
  { word: "请", pinyin: "qǐng", meaning: "招待する", lesson: 2 },
  { word: "晚饭", pinyin: "wǎnfàn", meaning: "晩ご飯", lesson: 2 },
  { word: "太～了", pinyin: "tài～le", meaning: "あまりに～である、すごく～である", answers: ["太～了", "太了"], lesson: 2 },
  { word: "高兴", pinyin: "gāoxìng", meaning: "うれしい", lesson: 2 },
  { word: "喜欢", pinyin: "xǐhuan", meaning: "好きである、好む", lesson: 2 },
  { word: "拉面", pinyin: "lāmiàn", meaning: "ラーメン", lesson: 2 },
  { word: "还是", pinyin: "háishi", meaning: "それとも", lesson: 2 },
  { word: "乌冬面", pinyin: "wūdōngmiàn", meaning: "うどん", lesson: 2 },
  { word: "可以", pinyin: "kěyǐ", meaning: "よろしい", lesson: 2 },
  { word: "知道", pinyin: "zhīdao", meaning: "知っている", lesson: 2 },
  { word: "家", pinyin: "jiā", meaning: "～軒", lesson: 2 },
  { word: "特别", pinyin: "tèbié", meaning: "とりわけ", lesson: 2 },
  { word: "爱吃", pinyin: "ài chī", meaning: "食べるのが好きである", lesson: 2 },

  { word: "不好意思", pinyin: "bù hǎoyìsi", meaning: "すみません", lesson: 3 },
  { word: "来晚", pinyin: "láiwǎn", meaning: "来るのが遅い", lesson: 3 },
  { word: "没事儿", pinyin: "méishìr", meaning: "大丈夫である", lesson: 3 },
  { word: "刚", pinyin: "gāng", meaning: "～したばかりである", lesson: 3 },
  { word: "哎呀", pinyin: "āiyā", meaning: "あら、まあ", lesson: 3 },
  { word: "这么", pinyin: "zhème", meaning: "こんなに", lesson: 3 },
  { word: "有名", pinyin: "yǒumíng", meaning: "有名である", lesson: 3 },
  { word: "网红店", pinyin: "wǎnghóngdiàn", meaning: "ネット上の有名店", lesson: 3 },
  { word: "酱油拉面", pinyin: "jiàngyóu lāmiàn", meaning: "醤油ラーメン", lesson: 3 },
  { word: "猪骨汤面", pinyin: "zhūgǔ tāngmiàn", meaning: "豚骨ラーメン", lesson: 3 },
  { word: "那", pinyin: "nà", meaning: "では、じゃあ", lesson: 3 },
  { word: "进去", pinyin: "jìnqu", meaning: "入っていく", lesson: 3 },

  { word: "点", pinyin: "diǎn", meaning: "注文する、オーダーする", lesson: 4 },
  { word: "套餐", pinyin: "tàocān", meaning: "セットメニュー、定食", lesson: 4 },
  { word: "碗", pinyin: "wǎn", meaning: "～杯", lesson: 4 },
  { word: "盘", pinyin: "pán", meaning: "～皿", lesson: 4 },
  { word: "炒饭", pinyin: "chǎofàn", meaning: "チャーハン", lesson: 4 },
  { word: "主食", pinyin: "zhǔshí", meaning: "主食", lesson: 4 },
  { word: "欢迎光临", pinyin: "huānyíng guānglín", meaning: "いらっしゃいませ", lesson: 4 },
  { word: "饮料", pinyin: "yǐnliào", meaning: "飲み物", lesson: 4 },
  { word: "杯", pinyin: "bēi", meaning: "～杯", lesson: 4 },
  { word: "可乐", pinyin: "kělè", meaning: "コーラ", lesson: 4 },
  { word: "无酒精啤酒", pinyin: "wújiǔjīng píjiǔ", meaning: "ノンアルコールビール", lesson: 4 },

  { word: "说", pinyin: "shuō", meaning: "言う、話す", lesson: 5 },
  { word: "得", pinyin: "de", meaning: "動詞や形容詞の後に置いて、補語を導く", lesson: 5 },
  { word: "真", pinyin: "zhēn", meaning: "本当に、実に", lesson: 5 },
  { word: "不行", pinyin: "bùxíng", meaning: "だめである", lesson: 5 },
  { word: "差得远", pinyin: "chàde yuǎn", meaning: "はるかに劣る", lesson: 5 },
  { word: "是～的", pinyin: "shì～de", meaning: "～のである", answers: ["是～的", "是的"], lesson: 5 },
  { word: "高一", pinyin: "gāoyī", meaning: "高校一年生", lesson: 5 },
  { word: "工作", pinyin: "gōngzuò", meaning: "仕事", lesson: 5 },
  { word: "怪不得", pinyin: "guàibude", meaning: "どうりで、なるほど", lesson: 5 },
  { word: "觉得", pinyin: "juéde", meaning: "～と思う", lesson: 5 },
  { word: "难", pinyin: "nán", meaning: "難しい", lesson: 5 },
  { word: "发音", pinyin: "fāyīn", meaning: "発音", lesson: 5 },

  { word: "快要～了", pinyin: "kuàiyào～le", meaning: "もうすぐ～である", answers: ["快要～了", "快要了"], lesson: 6 },
  { word: "暑假", pinyin: "shǔjià", meaning: "夏休み", lesson: 6 },
  { word: "打算", pinyin: "dǎsuàn", meaning: "～するつもりである", lesson: 6 },
  { word: "大连", pinyin: "Dàlián", meaning: "大連（地名）", lesson: 6 },
  { word: "听说", pinyin: "tīngshuō", meaning: "～だそうだ", lesson: 6 },
  { word: "凉快", pinyin: "liángkuai", meaning: "涼しい", lesson: 6 },
  { word: "多了", pinyin: "duō le", meaning: "ずっと～である", lesson: 6 },
  { word: "然后", pinyin: "ránhòu", meaning: "それから", lesson: 6 },
  { word: "旅游", pinyin: "lǚyóu", meaning: "旅行する", lesson: 6 },
  { word: "挣", pinyin: "zhèng", meaning: "お金を稼ぐ", lesson: 6 },
  { word: "学费", pinyin: "xuéfèi", meaning: "学費", lesson: 6 }
];
