"use strict";

// 出題データの原本。クイズ中は配列を複製して使用します。
const words = [
  { word: "礼堂", pinyin: "lǐtáng", meaning: "講堂、式場" },
  { word: "就", pinyin: "jiù", meaning: "まさに、まさしく" },
  { word: "参加", pinyin: "cānjiā", meaning: "参加する" },
  { word: "开学", pinyin: "kāixué", meaning: "学校が始まる" },
  { word: "典礼", pinyin: "diǎnlǐ", meaning: "儀式" },
  { word: "新生", pinyin: "xīnshēng", meaning: "新入生" },
  { word: "怎么", pinyin: "zěnme", meaning: "どうして" },
  { word: "穿", pinyin: "chuān", meaning: "着る" },
  { word: "西装", pinyin: "xīzhuāng", meaning: "スーツ、背広" },
  { word: "服装", pinyin: "fúzhuāng", meaning: "服装" },
  { word: "自由", pinyin: "zìyóu", meaning: "自由である" },
  { word: "好", pinyin: "hǎo", meaning: "非常に、なんと" },
  { word: "羡慕", pinyin: "xiànmù", meaning: "うらやむ" },
  { word: "一定", pinyin: "yídìng", meaning: "必ず" },

  { word: "晚上", pinyin: "wǎnshang", meaning: "晩、夜" },
  { word: "如果", pinyin: "rúguǒ", meaning: "もしも～" },
  { word: "方便", pinyin: "fāngbiàn", meaning: "便利である" },
  { word: "～的话", pinyin: "～dehua", meaning: "～ならば", answers: ["～的话", "的话"] },
  { word: "请", pinyin: "qǐng", meaning: "招待する" },
  { word: "晚饭", pinyin: "wǎnfàn", meaning: "晩ご飯" },
  { word: "太～了", pinyin: "tài～le", meaning: "あまりに～である、すごく～である", answers: ["太～了", "太了"] },
  { word: "高兴", pinyin: "gāoxìng", meaning: "うれしい" },
  { word: "喜欢", pinyin: "xǐhuan", meaning: "好きである、好む" },
  { word: "拉面", pinyin: "lāmiàn", meaning: "ラーメン" },
  { word: "还是", pinyin: "háishi", meaning: "それとも" },
  { word: "乌冬面", pinyin: "wūdōngmiàn", meaning: "うどん" },
  { word: "可以", pinyin: "kěyǐ", meaning: "よろしい" },
  { word: "知道", pinyin: "zhīdao", meaning: "知っている" },
  { word: "家", pinyin: "jiā", meaning: "～軒" },
  { word: "特别", pinyin: "tèbié", meaning: "とりわけ" },
  { word: "爱吃", pinyin: "ài chī", meaning: "食べるのが好きである" },

  { word: "不好意思", pinyin: "bù hǎoyìsi", meaning: "すみません" },
  { word: "来晚", pinyin: "láiwǎn", meaning: "来るのが遅い" },
  { word: "没事儿", pinyin: "méishìr", meaning: "大丈夫である" },
  { word: "刚", pinyin: "gāng", meaning: "～したばかりである" },
  { word: "哎呀", pinyin: "āiyā", meaning: "あら、まあ" },
  { word: "这么", pinyin: "zhème", meaning: "こんなに" },
  { word: "有名", pinyin: "yǒumíng", meaning: "有名である" },
  { word: "网红店", pinyin: "wǎnghóngdiàn", meaning: "ネット上の有名店" },
  { word: "酱油拉面", pinyin: "jiàngyóu lāmiàn", meaning: "醤油ラーメン" },
  { word: "猪骨汤面", pinyin: "zhūgǔ tāngmiàn", meaning: "豚骨ラーメン" },
  { word: "那", pinyin: "nà", meaning: "では、じゃあ" },
  { word: "进去", pinyin: "jìnqu", meaning: "入っていく" },

  { word: "点", pinyin: "diǎn", meaning: "注文する、オーダーする" },
  { word: "套餐", pinyin: "tàocān", meaning: "セットメニュー、定食" },
  { word: "碗", pinyin: "wǎn", meaning: "～杯" },
  { word: "盘", pinyin: "pán", meaning: "～皿" },
  { word: "炒饭", pinyin: "chǎofàn", meaning: "チャーハン" },
  { word: "主食", pinyin: "zhǔshí", meaning: "主食" },
  { word: "欢迎光临", pinyin: "huānyíng guānglín", meaning: "いらっしゃいませ" },
  { word: "饮料", pinyin: "yǐnliào", meaning: "飲み物" },
  { word: "杯", pinyin: "bēi", meaning: "～杯" },
  { word: "可乐", pinyin: "kělè", meaning: "コーラ" },
  { word: "无酒精啤酒", pinyin: "wújiǔjīng píjiǔ", meaning: "ノンアルコールビール" },

  { word: "说", pinyin: "shuō", meaning: "言う、話す" },
  { word: "得", pinyin: "de", meaning: "動詞や形容詞の後に置いて、補語を導く" },
  { word: "真", pinyin: "zhēn", meaning: "本当に、実に" },
  { word: "不行", pinyin: "bùxíng", meaning: "だめである" },
  { word: "差得远", pinyin: "chàde yuǎn", meaning: "はるかに劣る" },
  { word: "是～的", pinyin: "shì～de", meaning: "～のである", answers: ["是～的", "是的"] },
  { word: "高一", pinyin: "gāoyī", meaning: "高校一年生" },
  { word: "工作", pinyin: "gōngzuò", meaning: "仕事" },
  { word: "怪不得", pinyin: "guàibude", meaning: "どうりで、なるほど" },
  { word: "觉得", pinyin: "juéde", meaning: "～と思う" },
  { word: "难", pinyin: "nán", meaning: "難しい" },
  { word: "发音", pinyin: "fāyīn", meaning: "発音" },

  { word: "快要～了", pinyin: "kuàiyào～le", meaning: "もうすぐ～である", answers: ["快要～了", "快要了"] },
  { word: "暑假", pinyin: "shǔjià", meaning: "夏休み" },
  { word: "打算", pinyin: "dǎsuàn", meaning: "～するつもりである" },
  { word: "大连", pinyin: "Dàlián", meaning: "大連（地名）" },
  { word: "听说", pinyin: "tīngshuō", meaning: "～だそうだ" },
  { word: "凉快", pinyin: "liángkuai", meaning: "涼しい" },
  { word: "多了", pinyin: "duō le", meaning: "ずっと～である" },
  { word: "然后", pinyin: "ránhòu", meaning: "それから" },
  { word: "旅游", pinyin: "lǚyóu", meaning: "旅行する" },
  { word: "挣", pinyin: "zhèng", meaning: "お金を稼ぐ" },
  { word: "学费", pinyin: "xuéfèi", meaning: "学費" }
];
